baseURL = "https://www.bigclown.com/"
DefaultContentLanguage = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  menuNames = ["main","doc","support"]
  homeURL = "/"
  shopURL = "https://shop.bigclown.com/"
  productionURL = "https://www.bigclown.com"

[languages]
  [languages.en]
    LanguageName = "ENG"
    weight = 1
    [languages.en.params]
      baseURL = "/"
      shopURL = "https://shop.bigclown.com/"
      clownsletter = "a27d533e-3659-4331-a07e-80ada286f2c5"
  [languages.cs]
    LanguageName = "CZE"
    weight = 2
    [languages.cs.params]
      baseURL = "/cs/"
      shopURL = "https://obchod.bigclown.cz"
      clownsletter = "5585816d-f118-4a12-99a6-b82cf1a052fa"
      homeURL = "/cs/"

[blackfriday]
smartypants = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  level = "levels"
  place = "places"
  environment = "environmets"
  device = "devices"

[outputs]
        home = [ "HTML", "JSON"]
        page = [ "HTML"]
