backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "static/upload" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog EN" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Preview Image [788x544]", name: "image_preview", widget: "image"}
      - {label: "Main Image [cca 1400x510]", name: "image_main", widget: "image"}
      - {label: "Author", name: "author", widget: "select", options: ["martin_hubacek","pavel_hubner","michal_muhlpachr","alan_fabik","lukas_fabik"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog-cs" # Used in routes, e.g., /admin/collections/blog
    label: "Blog CS" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "cs.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Preview Image [788x544]", name: "image_preview", widget: "image"}
      - {label: "Main Image [cca 1400x510]", name: "image_main", widget: "image"}
      - {label: "Author", name: "author", widget: "select", options: ["martin_hubacek","pavel_hubner","michal_muhlpachr","alan_fabik","lukas_fabik"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects-en" # Used in routes, e.g., /admin/collections/blog
    label: "Projects EN" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", pattern: [".{,35}", "Must have max. 35 characters"]}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{,120}", "Must have max. 120 characters"]}
      - {label: "Environment", name: "tags", widget: "select", multiple: true, options: ["Indoor", "Outdoor"]}
      - {label: "Knowledge", name: "levels", widget: "select", multiple: true, options: ["Beginner","Advanced"]}
      - {label: "Place", name: "places", widget: "select", multiple: true, options: ["Home","Garden","Office"]}
      - {label: "Device", name: "devices", widget: "select", multiple: true, options: ["Custom Kit", "Motion Kit", "Flood Kit", "Power Kit"]}
      - {label: "Idea", name: "idea", widget: "boolean", required: false}
      - {label: "Preview Image [788x544]", name: "image_preview", widget: "image"}
      - {label: "Main Image [1400x460]", name: "image_main", widget: "image"}
      - {label: "Author", name: "author", widget: "select", options: ["martin_hubacek","pavel_hubner","michal_muhlpachr","alan_fabik","lukas_fabik"]}
      - {label: "Partner", name: "partner", widget: "string", required: false}
      - {label: "Partner Image [140x14O, 90x140, 140x90]", name: "partner_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects-cs" # Used in routes, e.g., /admin/collections/blog
    label: "Projects CS" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "cs.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", pattern: [".{,35}", "Must have max. 35 characters"]}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", pattern: [".{,120}", "Must have max. 120 characters"]}
      - {label: "Environment", name: "tags", widget: "select", multiple: true, options: ["Indoor", "Outdoor"]}
      - {label: "Knowledge", name: "levels", widget: "select", multiple: true, options: ["Beginner","Advanced"]}
      - {label: "Place", name: "places", widget: "select", multiple: true, options: ["Home","Garden","Office"]}
      - {label: "Device", name: "devices", widget: "select", options: ["Custom Kit", "Motion Kit", "Flood Kit", "Power Kit"]}
      - {label: "Idea", name: "idea", widget: "boolean", required: false}
      - {label: "Preview Image [788x544]", name: "image_preview", widget: "image"}
      - {label: "Main Image [1400x460]", name: "image_main", widget: "image"}
      - {label: "Author", name: "author", widget: "select", options: ["martin_hubacek","pavel_hubner","michal_muhlpachr","alan_fabik","lukas_fabik"]}
      - {label: "Partner", name: "partner", widget: "string", required: false}
      - {label: "Partner Image [140x14O, 90x140, 140x90]", name: "partner_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-basics-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Basics" # Used in the UI
    folder: "content/doc/basics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-documentation-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Documentation" # Used in the UI
    folder: "content/doc/documentation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-firmware-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Firmware" # Used in the UI
    folder: "content/doc/firmware" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-hardware-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Hardware" # Used in the UI
    folder: "content/doc/hardware" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-integrations-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Integrations" # Used in the UI
    folder: "content/doc/integrations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-interfaces-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Intefaces" # Used in the UI
    folder: "content/doc/interfaces" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-projects-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Projects" # Used in the UI
    folder: "content/doc/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-tools-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Tools" # Used in the UI
    folder: "content/doc/tools" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "doc-tutorials-en" # Used in routes, e.g., /admin/collections/blog
    label: "Doc - Tutorials" # Used in the UI
    folder: "content/doc/tutorials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
